"""nama_pengguna -> nama

Revision ID: aab1b0f1632a
Revises: c5730366d4c6
Create Date: 2022-04-04 21:53:17.210711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab1b0f1632a'
down_revision = 'c5730366d4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pengguna', sa.Column('nama', sa.String(length=64), nullable=False))
    op.drop_index('ix_pengguna_nama_pengguna', table_name='pengguna')
    op.create_index(op.f('ix_pengguna_nama'), 'pengguna', ['nama'], unique=True)
    op.drop_column('pengguna', 'nama_pengguna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pengguna', sa.Column('nama_pengguna', sa.VARCHAR(length=64), nullable=False))
    op.drop_index(op.f('ix_pengguna_nama'), table_name='pengguna')
    op.create_index('ix_pengguna_nama_pengguna', 'pengguna', ['nama_pengguna'], unique=False)
    op.drop_column('pengguna', 'nama')
    # ### end Alembic commands ###
