"""tabel surat

Revision ID: c5730366d4c6
Revises: ce0f6049edbb
Create Date: 2022-04-04 21:49:48.696879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5730366d4c6'
down_revision = 'ce0f6049edbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pesan', sa.String(length=140), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_tanggal'), 'surat', ['tanggal'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surat_tanggal'), table_name='surat')
    op.drop_table('surat')
    # ### end Alembic commands ###
